### ISSUE TITLE
If one bot is untrusted you lose the trusted dev badge

### ISSUE THREAD

**Issue by advaith1** [DiscordsBestBots/issues#16]

**Comment by IceeMC** [comment]
lmao this was fixed in the rewrite iirc

**Comment by IceeMC** [comment]
but whatever, its an easy fix

**Comment by IceeMC** [comment]
iirc its fixed

**Comment by advaith1** [comment]
fixed in v1? or just v2

**Comment by IceeMC** [comment]
well, it works like this if the owner owns no more trusted bots the owner loses the badge
