### ISSUE TITLE
I'm banned

### ISSUE THREAD

**Issue by Chewsterchew** [DiscordsBestBots/issues#20]
bro wtf (#19)

**Comment by advaith1** [comment]
NAB

**Comment by Chewsterchew** [comment]
NAB yourself why am I banned

**Comment by advaith1** [comment]
![GitHawk Upload by advaith1](https://i.imgur.com/dFncm8A.jpg)

For further info please ask @CaptainMarkley.

**Comment by Chewsterchew** [comment]
And would you please tell the jury what exactly was said?

**Comment by CaptainMarkley** [comment]
@Chewsterchew Fell free to DM me on Discord for any further interaction.

**Comment by Chewsterchew** [comment]
@CaptainMarkley No idea what your discord tag is, mind if you provide it?

**Comment by CaptainMarkley** [comment]
Google#0001
Would you not believe it...

**Comment by CaptainMarkley** [comment]
The screenshot has it so uhm...

**Comment by Chewsterchew** [comment]
The screenshot simply states, in my opinion, false information, no actual quotes of what were said are included.

**Comment by Chewsterchew** [comment]
Oh you meant the tag, sorry, didn't know that was you.

**Comment by IceeMC** [comment]
lmao

**Comment by Chewsterchew** [comment]
No.

**Comment by Chewsterchew** [comment]
That's @chewyiscrunchy

**Comment by chewyiscrunchy** [comment]
I was summoned by @chewsterchew

**Comment by Chewsterchew** [comment]
Surprise, these fools thought I made listcord

**Comment by chewyiscrunchy** [comment]
i see that

**Comment by Chewsterchew** [comment]
So how have you been lately and how did you get here so fast?

**Comment by chewyiscrunchy** [comment]
good i’m working on my advertising network and email notifications

**Comment by IceeMC** [comment]
I never said that you owned listcord

**Comment by Chewsterchew** [comment]
Sounds good, wasn't that the cookienet or whatever? I remember some logo being designed.

**Comment by Chewsterchew** [comment]
![image](https://user-images.githubusercontent.com/8278263/48681023-727fc300-eb65-11e8-80b1-3f3dead117e7.png)

![image](https://user-images.githubusercontent.com/8278263/48681024-76134a00-eb65-11e8-8c53-0109a5a7634c.png)

**Comment by chewyiscrunchy** [comment]
cookiescience but now it’s displaybutler because it makes more sense

**Comment by IceeMC** [comment]
I never said that you owned listcord

**Comment by chewyiscrunchy** [comment]
displaybutler.com

**Comment by advaith1** [comment]
Oof locked
