### ISSUE TITLE
My bot keeps getting deleted

### ISSUE THREAD

**Issue by Chewsterchew** [DiscordsBestBots/issues#21]
I keep submitting but it keeps getting removed

**Comment by Chewsterchew** [comment]
This could turn into either:
Let me know it was denied
or
Let me know it was deleted
or
Stop deleting my bot, I did nothing wrong.

**Comment by advaith1** [comment]
It was denied because you're banned

**Comment by Chewsterchew** [comment]
then unban me

**Comment by advaith1** [comment]
Ytho

**Comment by Chewsterchew** [comment]
so I can submit my bot

**Comment by advaith1** [comment]
@CaptainMarkley wants you to not submit your bot

**Comment by Chewsterchew** [comment]
why not?

**Comment by advaith1** [comment]
Ask them

**Comment by Chewsterchew** [comment]
Okay, so he's just gonna be like "I'd rather you not" then not explain why?

**Comment by Chewsterchew** [comment]
How do you propose I ask him if he doesn't want to talk to me and I'm banned from the server?

**Comment by Chewsterchew** [comment]
So, @CaptainMarkley, would you like to come here and explain why you supposedly "don't want me to submit my bot," or are you just gonna sit there and pretend I don't exist? Hint: You should probably do the first.

**Comment by Chewsterchew** [comment]
People already pretend I don't exist, so I'd rather you not be included with that group.
