### ISSUE TITLE
Vote and Report bork

### ISSUE THREAD

**Issue by MainUserDrive** [DiscordsBestBots/issues#35]
Trying to vote/report a bot from the bot's page is borken

Browser:
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

OS:
Windows 10 Home 64 bit

**Comment by IceeMC** [comment]
proof reee

**Comment by MainUserDrive** [comment]
How can i proove it tho?

**Comment by advaith1** [comment]
works fine for me on https://discordsbestbots.xyz/bots/advaithbot @MainUserDrive 
do you have any specific repro steps?

**Comment by MainUserDrive** [comment]
discordsbestbots.xyz > DiscordTel > Vote/Report

The exact steps I took for it to... bork

**Comment by advaith1** [comment]
cant repro
