### ISSUE TITLE
Profiles to have backgrounds

### ISSUE THREAD

**Issue by MainUserDrive** [DiscordsBestBots/issues#37]
So, on /profile, users should be able to 'edit' their page and set a background image. This might require more loads on the DB, but it would be cool if possible.

**Comment by IceeMC** [comment]
we have this already u meme

**Comment by MainUserDrive** [comment]
You do? Show.

**Comment by IceeMC** [comment]
its only for trusted devs, mods, and admins

**Comment by MainUserDrive** [comment]
https://pixelpikachu.tk/nrQZ5WFz.png
dont see anything

**Comment by IceeMC** [comment]
Maybe the image url is invalid. I see my bg clearly https://images.remixbot.ml/j8ONBrtK.png

**Comment by MainUserDrive** [comment]
I meant an edit button

**Comment by DetectiveHuman** [comment]
i disagree with you all

**Comment by IceeMC** [comment]
why?

**Comment by DetectiveHuman** [comment]
why not

**Comment by IceeMC** [comment]
shud I add you as an member of this org

**Comment by DetectiveHuman** [comment]
yes

**Comment by IceeMC** [comment]
ok
