### ISSUE TITLE
Modifying Profile Bug

### ISSUE THREAD

**Issue by StellaraUmbrix** [DiscordsBestBots/issues#38]
Typing in the Youtube field on the modify profile page modifies Instagram, and the other way around. (This must be a backend issue because Instagram and Youtube both modify the yt attribute)

What backend sees: https://pixelpikachu.tk/euCWpgtK.png
What frontend sees: https://pixelpikachu.tk/dPtoFtgR.png

**Comment by IceeMC** [comment]
so um, this isn’t a bug

**Comment by IceeMC** [comment]
wait nvm i forgot about that bug

**Comment by StellaraUmbrix** [comment]
Fixed
