### ISSUE TITLE
Backgrounds on bot pages can not be viewed

### ISSUE THREAD

**Issue by StellaraUmbrix** [DiscordsBestBots/issues#40]
( https://discordapp.com/channels/446682534135201793/530237912923766785/581774833164222465 )

**Comment by advaith1** [comment]
Why was this assigned to me I haven't seen the current code lmao

**Comment by ARandomApplePIe** [comment]
Idk ask Ice

**Comment by advaith1** [comment]
Fixed

**Comment by advaith1** [comment]
Fix is now live!
